- name: Include Red Hat tasks
  include: "{{ ansible_os_family }}.yml"
  static: no
  when: ansible_os_family == 'RedHat'

- name: add ssh key to authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', ssh_key + '.pub') }}"

- name: gather ec2 facts
  ec2_facts: 
